name: frontend
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.3.3"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_grpc_common:
    path: ../grpc/client
  hooks_riverpod: 
  riverpod_annotation: 
  json_annotation: 
  flutter_hooks: 
  freezed_annotation: 
  grpc: 
  flutter_slidable: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  riverpod_lint: 
  riverpod_generator: 
  freezed: 
  json_serializable:
  build_runner: 
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
